apiVersion: v2
name: runtime-rundown
description: A Helm chart for the Flux Training Application
type: application
version: 0.1.1
appVersion: "0.1.0"
keywords:
  - flux
  - training
  - golang
maintainers:
  - name: ro11net
    email: c.rolland@protonmail.com
home: https://github.com/ro11net/runtime-rundown
sources:
  - https://github.com/ro11net/runtime-rundown
dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
