{{- if not .Values.app.database.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runtime-rundown.fullname" . }}-db-secret
  labels:
    {{- include "runtime-rundown.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.app.database.password | b64enc | quote }}
{{- end }}

{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runtime-rundown.fullname" . }}-postgres-secret
  labels:
    {{- include "runtime-rundown.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  postgres-password: {{ .Values.postgres.env.POSTGRES_PASSWORD | b64enc | quote }}
{{- end }}
